SELECT * FROM employees

SELECT SALARY,
CASE WHEN SALARY <=65000.00 THEN 'LOW'
 WHEN SALARY  BETWEEN  65000.00 AND 85000.00 THEN 'MEDIUM'
 WHEN SALARY >85000.00 THEN 'HIGH'
END AS SALARY_2
FROM EMPLOYEES


SELECT  HIRE_DATE,
CASE WHEN YEAR ( HIRE_DATE) >= '2022' THEN 'Recent Hire'
ELSE 'Experienced'
END AS HIRE_DATE_2
FROM EMPLOYEES


SELECT SALARY,
CASE WHEN SALARY >80000.00 THEN 'Bonus Eligible'
ELSE  'Not Eligible'
END AS 'BONUS ELIGIBLE'
FROM EMPLOYEES




   SELECT HIRE_DATE, 
   CASE WHEN YEAR(HIRE_DATE)<' 2020' THEN 'SENIOR'
   WHEN YEAR (HIRE_DATE) BETWEEN '2020' AND '2022' THEN 'MID'
   WHEN YEAR (HIRE_DATE)>'2022'THEN 'JUNIOR'
   END AS 'STATUS'
   FROM EMPLOYEES

  '

   SELECT DEPARTMENT_ID,
   CASE WHEN DEPARTMENT_ID=3 THEN 'IT'
   ELSE 'NON_IT'
   END AS DEPARTMENT_2
   FROM EMPLOYEES


     SELECT SALARY,
   CASE WHEN SALARY<70000.00 THEN '10%INCREASE'
   WHEN SALARY BETWEEN 70000.00 AND 80000.00 THEN '5%INCREASE'
   WHEN SALARY>80000.00 THEN 'NO_INCREASE'
   END AS SALARY_INCREASE
   FROM EMPLOYEES


SELECT SALARY,
CASE WHEN SALARY<= 60000.00 THEN 'LOW'
WHEN SALARY BETWEEN 65000.00 AND 75000.00 THEN 'MEDIUM'
WHEN SALARY BETWEEN  75000.00 AND 90000.00 THEN 'HIGH'
END AS SALARY_RANGE
FROM EMPLOYEES
  
